[versions]
agp = "8.6.1"
kotlin = "1.9.24"
hilt = "2.51.1"
composeBom = "2024.06.00"

[libraries]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }